### ISSUE TITLE
lets make `funktion apply -f` and `funktion create -f` take *.flow files and creates flows so we can use a directory of flows and functions polymorphically

### ISSUE THREAD

**Issue by jstrachan** [funktionio/funktion#19]

**Comment by jimmidyson** [comment]
`.flow` extension is a bit annoying because it doesn't play nicely with highlighting or tooling in most editors without changing configuration. What do you think about `-flow.yml`?

**Comment by jstrachan** [comment]
Like it! 

I was initially gonna with just `.yml` but figured we may wanna mix and match real k8s YAML files with flow and functions all in a single folder some day (e.g. custom Service, Route, Ingress etc).

How about `.flow.yml` so its more clear its an 'extension' and folks don't use a combination of`-flow.yml`, `_flow.yml`, `.flow.yml`?

**Comment by jimmidyson** [comment]
:+1: We could then use `.connector.yml`, `.service.yml` if we need to define more types in this way. This is similar to angular 2 style guide for typescript files (e.g. `.component.ts`, `.module.ts`, etc) btw which works pretty nicely.

**Comment by jstrachan** [comment]
@jimmidyson great! I guess the only possibly confusing thing, there's the 'bare flow' YAML file, then there's the Flow inside a ConfigMap / ThirdPartyResource YAML which could be stored as a file too (not sure why - but it could). But then I guess the latter would just be a `.yml` file as it'd be a regular kubernetes resource file so doesn't need a different extension per se

**Comment by jimmidyson** [comment]
The file name is just an indicator I guess, we have to unmarshal/validate the content to see whether it's actually a flow or not.

**Comment by jimmidyson** [comment]
In other words, it's just a convention to simplify stuff for tooling.

**Comment by jstrachan** [comment]
yeah

**Comment by jstrachan** [comment]
at least now you can view flows nicely on github too :) https://github.com/jstrachan/funktion/tree/changes/examples/flow

**Comment by iocanel** [comment]
Anything else to be done here?

**Comment by jstrachan** [comment]
its mostly done now - just need to load the connectorName from the foo.flow.yml file
