### ISSUE TITLE
enable bash completion for commands

### ISSUE THREAD

**Issue by jstrachan** [funktionio/funktion#23]
it'd be really nice to enable bash completion like we can do with `kubectl` when using the commands. particularly for things like the names of functions / flows / connectors but also for other commands like kinds etc

**Comment by jstrachan** [comment]
instructions here: https://github.com/spf13/cobra/blob/master/bash_completions.md

**Comment by iocanel** [comment]
I added a command, for generates bash and zsh completion. 
I think that we just need to update the docs....

**Comment by iocanel** [comment]
Docs updated
