### ISSUE TITLE
When using OpenShift use oc vs. kubectl

### ISSUE THREAD

**Issue by nickschuetz** [funktionio/funktion#34]
It would be nice if funktion could use the oc command line interface that comes with OpenShift in addition to kubectl. Today this is what happens if you don't have kubectl installed and try to install the platform: 

```
$ funktion install platform
created Namespace funktion-system
Could not find executable at /usr/local/bin/kubectl
kubectl apply --namespace funktion-system -f https://repo1.maven.org/maven2/io/fabric8/platform/packages/funktion-platform/2.4.21/funktion-platform-2.4.21-kubernetes.yml
```

**Comment by bbrowning** [comment]
There's a TODO in the code to do just this - https://github.com/funktionio/funktion/blob/29e2c35685d62a16922cbd056dd7bd22505cee23/pkg/k8sutil/kubectl_helpers.go#L52-L55 . The challenge is figuring out whether or not the cluster is OpenShift. I don't see any obvious way with the `kubernetes.Clientset`passed to this method but there's likely some way to do it.
