### ISSUE TITLE
Kubernetes namespace creation should be handled diffferently under OpenShift

### ISSUE THREAD

**Issue by bbrowning** [funktionio/funktion#36]
When running inside of OpenShift, users typically won't have permission to create new Kubernetes namespaces. Detecting OpenShift and creating new OpenShift projects (which creates a new Kube namespace) is one alternative, although many OpenShift installs have a limit on the total number of projects a user can have.

You can specify an existing namespace to use with `funktion install platform` to partially workaround this issue. But, the `funktion-platform-2.4.21-kubernetes.yml` file also tries to create a `user-secrets-source-admin` namespace which will fail under OpenShift.

**Comment by jstrachan** [comment]
good catch. I've updated the installer to just reuse the current namespace now which makes it a little easier to use. e.g. we can now use funktion on openshift online. 

I've also removed that `user-secrets-source-admin` stuff which was a hangover from fabric8
