### ISSUE TITLE
Broken image links in documentation

### ISSUE THREAD

**Issue by apupier** [funktionio/funktion#42]
for instance here: https://funktion.fabric8.io/docs/#getting-started-with-funktion-and-the-jvm

![image](https://cloud.githubusercontent.com/assets/1105127/24703141/4682da98-1a02-11e7-9fed-842059deb806.png)

**Comment by jstrachan** [comment]
images are back now https://funktion.fabric8.io/docs/#getting-started-with-funktion-and-the-jvm - thanks @apupier

**Comment by apupier** [comment]
cool, thanks for the fast fix!
