### ISSUE TITLE
manual install instructions

### ISSUE THREAD

**Issue by trapexit** [funktionio/funktion#43]
The installation instructions all seem to be based on `funktion install`. Some K8s installs however are in private networks without net access.

**Comment by jstrachan** [comment]
yeah, we document how to install from a single YAML file really that folks could download or upload into an environment that doesn't have net access

**Comment by jstrachan** [comment]
I was hoping we could have a single URL that downloads the latest YAML; as each time we release the URL changes (as its got the version in it). e.g. to install via kubectl we could do:
```
kubectl apply -f http://central.maven.org/maven2/io/fabric8/platform/packages/funktion-platform/2.4.24/funktion-platform-2.4.24-kubernetes.yml
```

**Comment by jstrachan** [comment]
we've now a single YAML you can download and apply directly either for kubernetes:

```
kubectl apply -f http://central.maven.org/maven2/io/fabric8/funktion/packages/funktion-platform/3.0.3/funktion-platform-3.0.3-kubernetes.yml
```
or openshift:
```
oc apply -f http://central.maven.org/maven2/io/fabric8/funktion/packages/funktion-platform/3.0.3/funktion-platform-3.0.3-openshift.yml
```

those version numbers increase with every release here: http://central.maven.org/maven2/io/fabric8/funktion/packages/funktion-platform/
