### ISSUE TITLE
Installing Funktion in OpenShift Origin

### ISSUE THREAD

**Issue by hekonsek** [funktionio/funktion#44]
Hi,

I'm trying to install Funktion 1.0.10 into OpenShift Origin 1.4.1, but I got `User "admin" cannot get namespaces in project "user-secrets-source-admin"` error message.

```
$ oc login
... admin/admin ...

$ oc new-project xxx
...

$ funktion install platform --namespace xxx
oc apply --namespace xxx -f https://repo1.maven.org/maven2/io/fabric8/platform/packages/funktion-platform/2.4.24/funktion-platform-2.4.24-kubernetes.yml
serviceaccount "configmapcontroller" created
...
deployment "fabric8" created
deployment "funktion-operator" created
Error from server: User "admin" cannot get namespaces in project "user-secrets-source-admin"
Error from server: ConfigMap "catalog-letschat" is invalid: metadata.annotations: Too long: must have at most 262144 characters
Failed: exit status 1
```

Any suggestions on what could I do wrong here? :)

**Comment by cescoffier** [comment]
@hekonsek I face the same issue on different versions of OpenShift.
It seems to work with Kubernetes v1.6.0. 

So right now, I've switched to Minikube.

**Comment by hekonsek** [comment]
@cescoffier Good to know :) Thanks!

I'm wondering is there any information about the proper version of Kubernetes/Minikube/OpenShift that should be used with given version of Funktion? If not, maybe we should add this to documentation.

**Comment by cedricvidal** [comment]
I was facing the problem with Minikube 0.17.1 so I upgraded to Minikube 0.18.0


```
$ minikube version
minikube version: v0.18.0

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.1", GitCommit:"b0b7a323cc5a4a2019b2e9520c21c7830b7f708e", GitTreeState:"clean", BuildDate:"2017-04-03T23:37:30Z", GoVersion:"go1.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.0", GitCommit:"fff5156092b56e6bd60fff75aad4dc9de6b6ef37", GitTreeState:"dirty", BuildDate:"2017-04-07T20:46:46Z", GoVersion:"go1.7.3", Compiler:"gc", Platform:"linux/amd64"}
```
But when I rerun `funktion install platform` I still get the same error

```
The ConfigMap "catalog-letschat" is invalid: metadata.annotations: Too long: must have at most 262144 characters
```

@cescoffier What version of Minikube are you using ?

**Comment by cescoffier** [comment]
@cedricvidal I'm using the same version. However, what you see it just for the catalog. The runtime should work fine. Check the `ExposeController` logs, it's the tricky one....

**Comment by cedricvidal** [comment]
Hi @cescoffier , indeed, I wanted to answer my own comment but you beat me to it, I realized I could just ignore the warning and use the runtime without any problem so far. Thanx !

**Comment by hekonsek** [comment]
I still see exposer failing to start pod even for OpenShift Origin 1.5.0. 

Technically it seems that I can create function and flow, but in practice the flow is not deployed:

```
$ funktion create flow timer://bar?period=5000 http://hello/
2017/05/08 08:03:39 Flow timer-bar1 created timer://bar?period=5000 => http://hello/
$ funktion get flow
NAME                             PODS      STEPS
timer-bar1                                 timer://bar?period=5000 => http://hello/
```

It would be great to have somebody from Funktion team to comment on this, as we should support vanilla OpenShift Origin IMHO. :)

**Comment by hekonsek** [comment]
I have the same issues for Minishift 1.0.0 which comes with Origin 1.5.0. Exactly the same exposer pod error message:

```
F0508 10:00:37.413250       1 exposecontroller.go:66] failed to create new strategy: failed to create auto expose strategy: failed to automatically get exposer rule.  consider setting 'exposer' type in config.yml: failed to find any nodes: User "system:serviceaccount:funktion:exposecontroller" cannot list all nodes in the cluster
```

I assume that Funktion doesn't work with a recent OpenShift Origin / Minishift versions :( .

**Comment by jstrachan** [comment]
we've a new release which uses the current namespace only which makes things much easier on openshift; its been tested on OpenShift Online and the latest minishift and seems to work fine. 

Here's a little sample: https://github.com/funktionio/funktion-nodejs-quickstart/blob/master/README.md the [website](https://funktion.fabric8.io/) and [user guide](https://funktion.fabric8.io/docs/#install) have been updated to reflect this
