### ISSUE TITLE
Build - can't load package: package github.com/funktionio/funktion/cmd/operator

### ISSUE THREAD

**Issue by cescoffier** [funktionio/funktion#46]
I'm trying to build funktion, but I hit a compilation issue:

```
./scripts/check_license.sh
touch .check_license
go build -o funktion -ldflags="-X github.com/funktionio/funktion/pkg/version.version=1.0.10 -s -w -extldflags '-static'" github.com/funktionio/funktion/cmd/operator
can't load package: package github.com/funktionio/funktion/cmd/operator: cannot find package "github.com/funktionio/funktion/cmd/operator" in any of:
	/usr/local/opt/go/libexec/src/github.com/funktionio/funktion/cmd/operator (from $GOROOT)
	/Users/clement/dev/golang/src/github.com/funktionio/funktion/cmd/operator (from $GOPATH)
```

**Comment by jstrachan** [comment]
you ran the `make bootstrap` stuff first right to download stuff into the vendor folder?

I just ran it on my mac with
```
$glide -v
glide version 0.13.0-dev

$ go version
go version go1.7 darwin/amd64
```
and it all worked. I wondered if it was related to changes to glide or golang so upgraded to the latest golang and glide:
```
$glide -v
glide version v0.12.3

$ go version
go version go1.8.1 darwin/amd64

$ make
./scripts/check_license.sh
touch .check_license
go build -o funktion -ldflags="-X github.com/funktionio/funktion/pkg/version.version=1.0.10 -s -w -extldflags '-static'" github.com/funktionio/funktion/cmd/operator
```
and its working fine here. Does removing your vendor folder and re-running the `make boostrap; make` help at all? I wonder if `vendor` got corrupted or something?

**Comment by cescoffier** [comment]
@jstrachan and I have found the issue. Your repository structure must match `go/src/github.com/funktionio/funktion`.

Then you need 

```
GOPATH=.../go
GOHOME=.../go
```

Replace the `...` with the location you used as the root of the tree.
