### ISSUE TITLE
Error when trying the blog-example

### ISSUE THREAD

**Issue by rhuss** [funktionio/funktion#48]
The very first sample command fails (and I also tried several variations but to no avail):

```
funktion create fn -f examples/blog-example
Error: unknown shorthand flag: 'f' in -f
Usage:
  funktion create fn [flags]

Flags:
  -d, --debug               enable debugging for the function?
  -e, --env stringArray     pass one or more environment variables using the form NAME=VALUE
      --kubeconfig string   the directory to look for the kubernetes configuration
  -n, --name string         the name of the function to create
      --namespace string    the namespace to create the resource
  -r, --runtime string      the runtime to use. e.g. 'nodejs' (default "nodejs")
  -s, --source string       the source code of the function to create
  -w, --watch               whether to keep watching the files for changes to the function source code

unknown shorthand flag: 'f' in -f
```

**Comment by rhuss** [comment]
funktion version: 1.0.10

**Comment by jstrachan** [comment]
Thanks for the heads up! We don't yet have a `-f` option on `funktion create fn` though we can use `apply`.

```
$ funktion apply -f examples/blog-example
2017/06/09 10:58:01 Function blogcount created
2017/06/09 10:58:01 Function source created
2017/06/09 10:58:01 Function split created
```
Lemme add a `-f` to the `funktion create X` commands to avoid confusion from folks coming from a `kubectl / oc` background!

**Comment by rhuss** [comment]
btw, I just copied & pasted from the funktion.fabric8.io main page and also from 'get started' section in the docu which all refer to 'funktion create fn -f'

**Comment by rhuss** [comment]
And also in the blog example, there is a reference to 'funktion create fn -f'. So its not so much about confusion ;-)

**Comment by jstrachan** [comment]
great catch ;) yeah - need to fix up the docs - plus add `-f` ;)

@rhuss many thanks!
