### ISSUE TITLE
How to join Slack channel?

### ISSUE THREAD

**Issue by simoami** [funktionio/funktion#7]
Signups are disabled. One can only join by invite. Can you add me? simo at webinventinc dot com

**Comment by jstrachan** [comment]
huge apologies I'd missed your issue! (sorry when moving the organisations around I seem to have missed github notifications). I've just added you.

FWIW there's now an invite URL here: http://slack.fabric8.io/

**Comment by simoami** [comment]
@jstrachan awesome thanks!

**Comment by jstrachan** [comment]
I've just updated the home page to link to that invite URL too: https://funktion.fabric8.io/#about
